import type { Metadata } from "next";
import "./globals.css";
import { Space_Grotesk } from 'next/font/google'
import Navbar from "@/components/custom/navbar";
const font = Space_Grotesk({
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: "FlowPI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="rootBody" className={`${font.className} antialiased min-h-screen flex flex-col max-w-7xl !mx-auto !px-6 pb-12`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
